CARD_STATUS_ACTIVE = "ACTIVE"

COMMAND_INSERT_CARD = "INSERT_CARD"
COMMAND_REQUEST_BALANCE = "REQUEST_BALANCE"
COMMAND_REQUEST_WITHDRAW = "REQUEST_WITHDRAW"

FIELD_COMMAND_TYPE = "command_type"
FIELD_STATUS = "status"

RESULT_STATUS_OK = "ok"

ERROR_INVALID_STATE = "invalid state"
