CARD_STATUS_ACTIVE = "ACTIVE"
CARD_STATUS_INACTIVE = "INACTIVE"

COMMAND_INSERT_CARD = "INSERT_CARD"
COMMAND_REQUEST_BALANCE = "REQUEST_BALANCE"
COMMAND_REQUEST_WITHDRAW = "REQUEST_WITHDRAW"

FIELD_COMMAND_TYPE = "command_type"
FIELD_STATUS = "status"

RESULT_STATUS_OK = "ok"

ERROR_INVALID_STATE = "invalid state"
ERROR_INVALID_PIN = "Invalid PIN"
