CARD_STATUS_ACTIVE = "ACTIVE"

COMMAND_INSERT_CARD = "INSERT_CARD"
COMMAND_REQUEST_BALANCE = "REQUEST_BALANCE"
COMMAND_REQUEST_WITHDRAW = "REQUEST_WITHDRAW"

RESULT_STATUS_OK = "ok"

ERROR_INVALID_STATE = "invalid state"
