TRANSPORT_ROOT_ENV = "BANKING_TRANSPORT_ROOT"
TRANSPORT_REQUESTS_DIR = "requests"
TRANSPORT_RESPONSES_DIR = "responses"
TRANSPORT_FILE_SUFFIX = ".json"

WORKER_MODE_ERROR = "error"
WORKER_MODE_SUCCESS = "success"
